# Generated by Django 4.1.3 on 2022-11-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=122)),
                ('number_of_integers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=122)),
                ('position', models.CharField(max_length=122)),
                ('education', models.TextField()),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamapp.department')),
            ],
        ),
    ]
