# Generated by Django 4.1.3 on 2022-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0002_department_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
