# Generated by Django 4.1.3 on 2022-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0006_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='department_name',
        ),
    ]
