# Generated by Django 4.1.3 on 2022-11-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0008_remove_department_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
    ]
