# Generated by Django 4.1.3 on 2022-11-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0010_rename_position_doctor_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
