# Generated by Django 4.1.3 on 2022-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0011_remove_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.TextField()),
                ('patient_name', models.TextField()),
                ('apppointment_date', models.DateField()),
            ],
        ),
    ]
