# Generated by Django 4.1.3 on 2022-11-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0012_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apppointment_date',
            field=models.TextField(),
        ),
    ]
