# Generated by Django 4.1.3 on 2022-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0014_admit'),
    ]

    operations = [
        migrations.AddField(
            model_name='admit',
            name='name',
            field=models.TextField(default='shubham'),
        ),
    ]
