# Generated by Django 4.1.3 on 2022-11-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0016_discharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_no',
            new_name='room_charge',
        ),
    ]
