# Generated by Django 4.1.3 on 2022-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0017_rename_room_no_rooms_room_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_desc',
            field=models.TextField(default='Shubham'),
            preserve_default=False,
        ),
    ]
